require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PlantCategoriesController do

  # This should return the minimal set of attributes required to create a valid
  # PlantCategory. As you add validations to PlantCategory, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all plant_categories as @plant_categories" do
      plant_category = PlantCategory.create! valid_attributes
      get :index
      assigns(:plant_categories).should eq([plant_category])
    end
  end

  describe "GET show" do
    it "assigns the requested plant_category as @plant_category" do
      plant_category = PlantCategory.create! valid_attributes
      get :show, :id => plant_category.id.to_s
      assigns(:plant_category).should eq(plant_category)
    end
  end

  describe "GET new" do
    it "assigns a new plant_category as @plant_category" do
      get :new
      assigns(:plant_category).should be_a_new(PlantCategory)
    end
  end

  describe "GET edit" do
    it "assigns the requested plant_category as @plant_category" do
      plant_category = PlantCategory.create! valid_attributes
      get :edit, :id => plant_category.id.to_s
      assigns(:plant_category).should eq(plant_category)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PlantCategory" do
        expect {
          post :create, :plant_category => valid_attributes
        }.to change(PlantCategory, :count).by(1)
      end

      it "assigns a newly created plant_category as @plant_category" do
        post :create, :plant_category => valid_attributes
        assigns(:plant_category).should be_a(PlantCategory)
        assigns(:plant_category).should be_persisted
      end

      it "redirects to the created plant_category" do
        post :create, :plant_category => valid_attributes
        response.should redirect_to(PlantCategory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved plant_category as @plant_category" do
        # Trigger the behavior that occurs when invalid params are submitted
        PlantCategory.any_instance.stub(:save).and_return(false)
        post :create, :plant_category => {}
        assigns(:plant_category).should be_a_new(PlantCategory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PlantCategory.any_instance.stub(:save).and_return(false)
        post :create, :plant_category => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested plant_category" do
        plant_category = PlantCategory.create! valid_attributes
        # Assuming there are no other plant_categories in the database, this
        # specifies that the PlantCategory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PlantCategory.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => plant_category.id, :plant_category => {'these' => 'params'}
      end

      it "assigns the requested plant_category as @plant_category" do
        plant_category = PlantCategory.create! valid_attributes
        put :update, :id => plant_category.id, :plant_category => valid_attributes
        assigns(:plant_category).should eq(plant_category)
      end

      it "redirects to the plant_category" do
        plant_category = PlantCategory.create! valid_attributes
        put :update, :id => plant_category.id, :plant_category => valid_attributes
        response.should redirect_to(plant_category)
      end
    end

    describe "with invalid params" do
      it "assigns the plant_category as @plant_category" do
        plant_category = PlantCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PlantCategory.any_instance.stub(:save).and_return(false)
        put :update, :id => plant_category.id.to_s, :plant_category => {}
        assigns(:plant_category).should eq(plant_category)
      end

      it "re-renders the 'edit' template" do
        plant_category = PlantCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PlantCategory.any_instance.stub(:save).and_return(false)
        put :update, :id => plant_category.id.to_s, :plant_category => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested plant_category" do
      plant_category = PlantCategory.create! valid_attributes
      expect {
        delete :destroy, :id => plant_category.id.to_s
      }.to change(PlantCategory, :count).by(-1)
    end

    it "redirects to the plant_categories list" do
      plant_category = PlantCategory.create! valid_attributes
      delete :destroy, :id => plant_category.id.to_s
      response.should redirect_to(plant_categories_url)
    end
  end

end
