require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProjectStatusesController do

  # This should return the minimal set of attributes required to create a valid
  # ProjectStatus. As you add validations to ProjectStatus, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all project_statuses as @project_statuses" do
      project_status = ProjectStatus.create! valid_attributes
      get :index
      assigns(:project_statuses).should eq([project_status])
    end
  end

  describe "GET show" do
    it "assigns the requested project_status as @project_status" do
      project_status = ProjectStatus.create! valid_attributes
      get :show, :id => project_status.id.to_s
      assigns(:project_status).should eq(project_status)
    end
  end

  describe "GET new" do
    it "assigns a new project_status as @project_status" do
      get :new
      assigns(:project_status).should be_a_new(ProjectStatus)
    end
  end

  describe "GET edit" do
    it "assigns the requested project_status as @project_status" do
      project_status = ProjectStatus.create! valid_attributes
      get :edit, :id => project_status.id.to_s
      assigns(:project_status).should eq(project_status)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProjectStatus" do
        expect {
          post :create, :project_status => valid_attributes
        }.to change(ProjectStatus, :count).by(1)
      end

      it "assigns a newly created project_status as @project_status" do
        post :create, :project_status => valid_attributes
        assigns(:project_status).should be_a(ProjectStatus)
        assigns(:project_status).should be_persisted
      end

      it "redirects to the created project_status" do
        post :create, :project_status => valid_attributes
        response.should redirect_to(ProjectStatus.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved project_status as @project_status" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProjectStatus.any_instance.stub(:save).and_return(false)
        post :create, :project_status => {}
        assigns(:project_status).should be_a_new(ProjectStatus)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProjectStatus.any_instance.stub(:save).and_return(false)
        post :create, :project_status => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested project_status" do
        project_status = ProjectStatus.create! valid_attributes
        # Assuming there are no other project_statuses in the database, this
        # specifies that the ProjectStatus created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProjectStatus.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => project_status.id, :project_status => {'these' => 'params'}
      end

      it "assigns the requested project_status as @project_status" do
        project_status = ProjectStatus.create! valid_attributes
        put :update, :id => project_status.id, :project_status => valid_attributes
        assigns(:project_status).should eq(project_status)
      end

      it "redirects to the project_status" do
        project_status = ProjectStatus.create! valid_attributes
        put :update, :id => project_status.id, :project_status => valid_attributes
        response.should redirect_to(project_status)
      end
    end

    describe "with invalid params" do
      it "assigns the project_status as @project_status" do
        project_status = ProjectStatus.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProjectStatus.any_instance.stub(:save).and_return(false)
        put :update, :id => project_status.id.to_s, :project_status => {}
        assigns(:project_status).should eq(project_status)
      end

      it "re-renders the 'edit' template" do
        project_status = ProjectStatus.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProjectStatus.any_instance.stub(:save).and_return(false)
        put :update, :id => project_status.id.to_s, :project_status => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested project_status" do
      project_status = ProjectStatus.create! valid_attributes
      expect {
        delete :destroy, :id => project_status.id.to_s
      }.to change(ProjectStatus, :count).by(-1)
    end

    it "redirects to the project_statuses list" do
      project_status = ProjectStatus.create! valid_attributes
      delete :destroy, :id => project_status.id.to_s
      response.should redirect_to(project_statuses_url)
    end
  end

end
